"""Taste profile loader for AI Autopilot (v2).

Loads, validates, and queries the taste profile generated by Opus 4.6.
The profile is a JSON document describing genre weights, energy profiles,
creator affinity, and discovery queries. It's stored in the autopilot_profile
DB table.

v2 changes: energy_profiles replace block_strategies, discovery_queries are
global (not per-block), and creator_affinity + avoid_patterns are new.
"""

import json
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

# Required top-level keys in a valid v2 taste profile
_REQUIRED_KEYS = {"version", "generated_at", "global_preferences", "energy_profiles"}

# Valid energy profile names
_ENERGY_PROFILES = {"chill", "focus", "vibes"}


class TasteProfileError(Exception):
    """Raised when a taste profile is invalid or cannot be loaded."""


class TasteProfile:
    """Loads and queries a taste profile from the database.

    The profile JSON is generated by Opus 4.6 on Mac and synced
    to Pi via rsync or the /api/autopilot/profile endpoint.
    """

    def __init__(self):
        self._profile: dict | None = None
        self._generated_at: datetime | None = None
        self._loaded_at: datetime | None = None
        self._version: int = 0

    @property
    def is_loaded(self) -> bool:
        return self._profile is not None

    @property
    def generated_at(self) -> datetime | None:
        return self._generated_at

    @property
    def version(self) -> int:
        return self._version

    def load(self, db) -> dict | None:
        """Load the most recent taste profile from the database.

        Returns the profile dict if found and valid, None otherwise.
        """
        row = db.fetchone(
            "SELECT profile_json, generated_at, loaded_at, version "
            "FROM autopilot_profile WHERE id = 1"
        )
        if row is None:
            logger.info("No taste profile found in database")
            self._profile = None
            return None

        try:
            profile = json.loads(row["profile_json"])
        except (json.JSONDecodeError, TypeError) as e:
            logger.error("Invalid taste profile JSON: %s", e)
            self._profile = None
            return None

        missing = _REQUIRED_KEYS - set(profile.keys())
        if missing:
            logger.error("Taste profile missing required keys: %s", missing)
            self._profile = None
            return None

        self._profile = profile
        self._version = row["version"]
        try:
            self._generated_at = datetime.fromisoformat(row["generated_at"])
        except (ValueError, TypeError):
            self._generated_at = None
        try:
            self._loaded_at = datetime.fromisoformat(row["loaded_at"])
        except (ValueError, TypeError):
            self._loaded_at = None

        logger.info(
            "Loaded taste profile v%d (generated %s)",
            self._version,
            row["generated_at"],
        )
        return self._profile

    def is_stale(self, threshold_hours: int = 48) -> bool:
        """Check if the profile is older than threshold_hours.

        Returns True if no profile is loaded or if it's too old.
        """
        if self._generated_at is None:
            return True

        generated = self._generated_at
        if generated.tzinfo is None:
            generated = generated.replace(tzinfo=timezone.utc)

        now = datetime.now(timezone.utc)
        age_hours = (now - generated).total_seconds() / 3600
        return age_hours > threshold_hours

    def get_energy_profile(self, mood: str) -> dict:
        """Get the energy profile for a mood (chill/focus/vibes).

        Returns empty dict if no profile or mood not found.
        """
        if self._profile is None:
            return {}
        profiles = self._profile.get("energy_profiles", {})
        return dict(profiles.get(mood, {}))

    def get_genre_weights(self) -> dict[str, float]:
        """Get global genre weights from the profile.

        Returns empty dict if no profile loaded.
        """
        if self._profile is None:
            return {}
        prefs = self._profile.get("global_preferences", {})
        return dict(prefs.get("genre_weights", {}))

    def get_discovery_queries(self) -> list[str]:
        """Get global discovery search queries.

        Returns empty list if no profile or no queries.
        """
        if self._profile is None:
            return []
        queries = self._profile.get("discovery_queries", [])
        return list(queries)

    def get_creator_affinity(self) -> dict[str, float]:
        """Get creator/channel affinity weights.

        Returns empty dict if no profile or no creator data.
        Values: 1.0 = neutral, >1.0 = prefer, <1.0 = de-prioritize.
        """
        if self._profile is None:
            return {}
        return dict(self._profile.get("creator_affinity", {}))

    def get_avoid_patterns(self) -> list[str]:
        """Get patterns to filter out from selection.

        Returns empty list if no profile or no patterns.
        """
        if self._profile is None:
            return []
        return list(self._profile.get("avoid_patterns", []))

    def save(self, db, profile_json: str, generated_at: str) -> None:
        """Save a new taste profile to the database.

        Upserts the single profile row (id=1).

        Args:
            db: Database instance
            profile_json: Raw JSON string of the profile
            generated_at: ISO 8601 timestamp of when the profile was generated
        """
        # Validate JSON before saving
        try:
            parsed = json.loads(profile_json)
        except (json.JSONDecodeError, TypeError) as e:
            raise TasteProfileError(f"Invalid profile JSON: {e}") from e

        missing = _REQUIRED_KEYS - set(parsed.keys())
        if missing:
            raise TasteProfileError(
                f"Profile missing required keys: {missing}"
            )

        version = parsed.get("version", 1)

        db.execute(
            "INSERT INTO autopilot_profile (id, profile_json, generated_at, version) "
            "VALUES (1, ?, ?, ?) "
            "ON CONFLICT(id) DO UPDATE SET "
            "profile_json = excluded.profile_json, "
            "generated_at = excluded.generated_at, "
            "loaded_at = datetime('now'), "
            "version = excluded.version",
            (profile_json, generated_at, version),
        )
        db.commit()

        # Reload into memory
        self.load(db)

    def to_dict(self) -> dict:
        """Return a summary dict for API responses."""
        return {
            "loaded": self.is_loaded,
            "version": self._version,
            "generated_at": (
                self._generated_at.isoformat() if self._generated_at else None
            ),
            "stale": self.is_stale(),
            "energy_profiles": (
                list(self._profile.get("energy_profiles", {}).keys())
                if self._profile
                else []
            ),
        }
